---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.11
  - name: debian-8.9
  - name: debian-9.0

suites:
  - name: default
    run_list:
      - recipe[t3-chef-vault::default]
    attributes:
